PUT http://localhost:8080/api/article?id=1
Content-Type: application/json

{
  "title": "Lorem",
  "headline": "Ipsum",
  "content": "This is the content",
  "author": {
    "login": "alex",
    "firstname": "Alex",
    "lastname": "Moe",
    "id": 1
  }
}

###
POST http://localhost:8080/api/article
Content-Type: application/json

{
  "title": "Loremm",
  "headline": "Ipsumm",
  "content": "This is the awesome content",
  "author": {
    "login": "john_doe",
    "firstname": "John",
    "lastname": "Doe",
    "id": 1
  }
}

###
GET http://localhost:8080/api/article/
Accept: application/json

###
GET http://localhost:8080/api/user/
Accept: application/json

###
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "login": "john_doe",
  "firstname": "John",
  "lastname": "Doe"
}
